---
- hosts: MesosMasters
  sudo: yes
  user: root
  roles:
   - installJavaEight
   - installMesosMasters
   - configureZKOnMasters
   - configureMesosMasters

- hosts: MesosSlaves
  sudo: yes
  user: root
  roles:
   - installMesosSlaves
 
- hosts: MesosSlaves
  sudo: yes
  user: root
  roles:
   - configureZKOnSlaves
 
- hosts: MesosMasters
  sudo: yes
  user: root
  roles:
   - restartZKOnMasters
   - configureMarathonOnMasters

- hosts: MesosSlaves
  sudo: yes
  user: root
  roles:
   - configureMesosSlaves
