---
- name: Add apt-key
  apt_key: id=E56151BF keyserver=keyserver.ubuntu.com state=present

- name: Add Mesosphere Repository
  apt_repository: repo='deb http://repos.mesosphere.io/{{ansible_distribution|lower}} {{ansible_distribution_release|lower}} main' state=present

- name: Update local repo cache
  apt: update_cache=yes

- name: Install Mesosphere
  apt: pkg=mesos state=installed update_cache=true

- name: Install Marathon
  apt: pkg=marathon state=installed update_cache=true

