---
- name: stop ZK
  service: name=zookeeper state=stopped

- name: stop marathon
  service: name=marathon state=stopped

- name: stop Mesos Master
  service: name=mesos-master state=stopped

- name: start ZK
  service: name=zookeeper state=started

- name: start marathon
  service: name=marathon state=started

- name: start Mesos Master
  service: name=mesos-master state=started
